/* eslint-disable @next/next/no-img-element */
import Layout from '@/components/Layout'
import Image from 'next/image'
import React from 'react'

const ImageOptimization = () => {
  return (
    <Layout pageTitle='Image Optimization Page'>
      <Image src="/bromo1.jpg" width={200} height={200} alt="test image 1" />
      <img src="/bromo1.jpg" style={{ width: 200, height: 200 }} alt="test image 1" />
      <div>Image Optimization</div>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      
      <Image src="/bromo2.png" width={200} height={200} alt="test image 1" />
      <img src="/bromo2.png" style={{ width: 200, height: 200 }} alt="test image 1" />
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Sequi possimus architecto dolores praesentium voluptatibus itaque eaque id minus unde quas aliquid aliquam esse explicabo ullam reiciendis consectetur eligendi, natus facere.</p>
      <Image src="/bromo3.jpg" width={200} height={200} alt="test image 1" />
      <img src="/bromo3.jpg" style={{ width: 200, height: 200 }} alt="test image 1" />
    </Layout>

  )
}

export default ImageOptimization